common: &common
  adapter: postgresql
  encoding: utf8

local: &local
  <<: *common
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *local
  database: encore_backend_development

test:
  <<: *local
  database: encore_backend_test

# Dummy because Heroku will replace
production:
  <<: *common