#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: encore-backend-production
  config:
    RACK_ENV: production
    RAILS_ENV: production
  addons:
    - redistogo:nano

staging:
  app: encore-backend-staging
  config:
    RACK_ENV: staging
    RAILS_ENV: staging
  addons:
    - redistogo:nano